# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 13:36
from __future__ import unicode_literals

import api.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('md5', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(32)])),
                ('completed', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', api.models.PositiveBigIntegerField()),
                ('name', models.TextField()),
                ('offset', api.models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('addr', api.models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Libs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', api.models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vex_hash', models.CharField(max_length=536, validators=[django.core.validators.MinLengthValidator(536)])),
                ('flow_hash', models.CharField(max_length=280, validators=[django.core.validators.MinLengthValidator(280)])),
                ('raw', models.BinaryField()),
                ('raw_len', models.IntegerField()),
                ('name', models.TextField()),
                ('callconv', models.TextField(null=True)),
                ('apicalls', models.TextField()),
                ('asm', models.BinaryField()),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Procedure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('sha256', models.CharField(db_index=True, max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(64)])),
                ('md5', models.CharField(max_length=32, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(32)])),
            ],
        ),
        migrations.CreateModel(
            name='ProgramInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('bits', models.PositiveSmallIntegerField()),
                ('arch', models.TextField()),
                ('program_class', models.TextField()),
                ('endian', models.TextField()),
                ('entropy', models.IntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', api.models.PositiveBigIntegerField()),
                ('name', models.TextField(null=True)),
                ('md5', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(32)])),
                ('offset', api.models.PositiveBigIntegerField()),
                ('programinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ProgramInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Strings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', api.models.PositiveBigIntegerField()),
                ('encoding', models.TextField()),
                ('val', models.TextField()),
                ('offset', api.models.PositiveBigIntegerField()),
                ('programinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ProgramInfo')),
            ],
        ),
        migrations.AddField(
            model_name='procedurecomment',
            name='procedureDesc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ProcedureDesc'),
        ),
        migrations.AddField(
            model_name='procedurecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedure',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Program'),
        ),
        migrations.AddField(
            model_name='libs',
            name='programinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ProgramInfo'),
        ),
        migrations.AddField(
            model_name='import',
            name='programinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ProgramInfo'),
        ),
        migrations.AddField(
            model_name='exports',
            name='programinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ProgramInfo'),
        ),
        migrations.AlterUniqueTogether(
            name='proceduredesc',
            unique_together=set([('procedure', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='procedure',
            unique_together=set([('offset', 'program')]),
        ),
    ]
