# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programinfo',
            name='program_class',
            field=models.TextField(blank=True, null=True),
        ),
    ]
