# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_proceduredescdownvote_proceduredescupvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proceduredesccommentdownvote',
            old_name='proc_desc_comment',
            new_name='procedure_desc_comment',
        ),
        migrations.RenameField(
            model_name='proceduredesccommentupvote',
            old_name='proc_desc_comment',
            new_name='procedure_desc_comment',
        ),
        migrations.RenameField(
            model_name='proceduredescdownvote',
            old_name='proc_desc',
            new_name='procedure_desc',
        ),
        migrations.RenameField(
            model_name='proceduredescupvote',
            old_name='proc_desc',
            new_name='procedure_desc',
        ),
    ]
