# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180318_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduredesc',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
