# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 14:53
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('email_verification_token', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(32)])),
                ('email_verification_token_creation_date', models.DateTimeField(null=True)),
                ('reset_email_token', models.CharField(max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(32)])),
                ('reset_email_token_creation_date', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
