# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profileoauth2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileoauth2',
            name='creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
