# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-18 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180214_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
