# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 10:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(default='http://www.pvhc.net/img240/uyttxprhsqycyximpzjb.png', max_length=256),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reset_email_token',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(32)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reset_email_token_creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
