# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180219_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(default='/Carbonara/frontend/uyttxprhsqycyximpzjb[1].png', max_length=256),
        ),
    ]
