# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_votenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='votenotification',
            name='creation_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
