# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_votenotification_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votenotification',
            old_name='creation_data',
            new_name='creation_date',
        ),
    ]
