# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-21 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180420_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile_image/default-profile-image.png', upload_to='profile_image'),
        ),
    ]
